version = 1

test_patterns = ["test/**"]

exclude_patterns = [
    "contracts/**",
    "docs/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  ecma_version = "2020"
  module_system = "commonjs"
  style_guide = "standard"
  environment = [
    "nodejs",
    "browser"
  ]
